services:
  - name: app
    env:
      - key: PORT
        value: 3000
      # Add other environment variables here like DB_USER, DB_PASSWORD, etc.

buildCommand: npm install && npm run build
startCommand: node src/server.js

